### ISSUE TITLE
Can't handle empty subtitle entries

### ISSUE THREAD

**Issue by xd009642** [GavalasDev/srtlib#10]
I have a subtitle file where within it there's this chunk:

```
365
00:23:01,466 --> 00:23:05,466
おりゃーっ！

366
00:23:12,477 --> 00:23:20,818


367
00:23:20,819 --> 00:23:23,519
おりゃーっ！
```

And it throws an error on 366 and later in the file when there's another blank subtitle. It should be a relatively easy fix and I'll look at potentially doing a PR, just raising the issue first!

**Comment by GavalasDev** [comment]
Thanks for raising the issue! Do let me know if you need any help or if you'd like me to take over instead.
