### ISSUE TITLE
Can't parse srt files whose timestamp is "HH:MM:SS.XXX"

### ISSUE THREAD

**Issue by kkew3** [GavalasDev/srtlib#9]
The `Subtitles::parse_from_str` seems to fail into dead loop when the separator between second and millisecond is '.' instead of ','. However, video player like [IINA](https://iina.io) supports both formats. Therefore, I believe this could be a bug.

**Comment by GavalasDev** [comment]
Thanks for letting me know. I had never heard of this before, but it's apparently implemented in most players (I also tested mpv) and it's an easy fix on my end.

**Comment by kkew3** [comment]
Thank you so much!
